services:
  mysql:
    image: mysql:8.4.5
    container_name: lv3-final-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - lv3-final-mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  lv3-final-mysql-data:
