spring:
  config:
    activate:
      on-profile: default,local

  application:
    name: lv3-final-mission

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    access-token:
      secret-key: since-jjwt-api-0.11-secret-key-must-be-longer-than-32-bytes
      validity-in-milliseconds: 900000 # 15 minutes

email:
  twilio:
    base-url: https://api.sendgrid.com/v3/mail/send
    secret-key: ${TWILIO_EMAIL_API_KEY}
