spring:
  config:
    import: optional:application-secret.yml
  application:
    name: lv2-final-mission

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

security:
  jwt:
    access-token:
      secret-key: since-jjwt-api-0.11-secret-key-must-be-longer-than-32-bytes
      validity-in-milliseconds: 900000 # 15 minutes

